definitions:
  dto.FileDTO:
    properties:
      content:
        example: <?php echo 1;?>
        type: string
      name:
        example: class
        type: string
    type: object
  dto.GistRequestBody:
    properties:
      description:
        example: Gist short description
        type: string
      files:
        items:
          $ref: '#/definitions/dto.FileDTO'
        type: array
      is_public:
        example: true
        type: boolean
      name:
        example: class
        type: string
    type: object
  dto.GistResponse:
    properties:
      description:
        example: Gist short description
        type: string
      files:
        items:
          $ref: '#/definitions/dto.FileDTO'
        type: array
      forks:
        type: integer
      id:
        type: integer
      is_public:
        example: true
        type: boolean
      name:
        example: class
        type: string
      stars:
        type: integer
    type: object
  handlers.ResponseHTTP:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/gists:
    get:
      consumes:
      - application/json
      description: Get list of public gists
      parameters:
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.GistResponse'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ResponseHTTP'
      summary: Get list of gists
      tags:
      - gists
    post:
      consumes:
      - application/json
      description: Register gist
      parameters:
      - description: Register gist
        in: body
        name: gist
        required: true
        schema:
          $ref: '#/definitions/dto.GistRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/dto.GistResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ResponseHTTP'
      summary: Register a new gist
      tags:
      - gists
  /api/v1/gists/{id}:
    get:
      consumes:
      - application/json
      description: Get gist by ID
      parameters:
      - description: Gist ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.GistResponse'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ResponseHTTP'
      summary: Get gist by ID
      tags:
      - gists
swagger: "2.0"
